# Docker
docker-hub-email: soufianem370@gmail.com
docker-hub-username: soufianem370
docker-hub-password: M@na198654
docker-hub-repo-name: web

# Kubernetes
server: <<API SERVER URI>>
namespace: <<NAMESPACE>>
cad: <<CERT AUTH DATA>>
token: <<K8 TOKEN>>
